version: '3.1'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: micro_yt
  eureka:
    image: openjdk:17.0.2-jdk-oracle
    command: java -jar /app/application.jar
    ports:
      - 8000:8761
    environment:
      - DISCOVERY_HOST=eureka
    volumes:
      - ./ServiceRegistry/ServiceRegistry/target/ServiceRegistry-0.0.1-SNAPSHOT.jar:/app/application.jar
  quiz-service:
    image: openjdk:17.0.2-jdk-oracle
    command: java -jar /app/application.jar
    environment:
      - DB_HOST=db
      - DB_DATABASE=micro_yt
      - DISCOVERY_URL=http://eureka:8761/eureka
      - DISCOVERY_HOST=eureka
    depends_on:
      - db
    volumes:
      - ./QuizService/QuizService/target/QuizService-0.0.1-SNAPSHOT.jar:/app/application.jar
  question-service:
    image: openjdk:17.0.2-jdk-oracle
    command: java -jar /app/application.jar
    environment:
      - DB_HOST=db
      - DB_DATABASE=micro_yt
      - DISCOVERY_URL=http://eureka:8761/eureka
      - DISCOVERY_HOST=eureka
    depends_on:
      - db
    volumes:
      - ./QuestionService/QuestionService/target/QuestionService-0.0.1-SNAPSHOT.jar:/app/application.jar
  api-gateway:
    image: openjdk:17.0.2-jdk-oracle
    command: java -jar /app/application.jar
    ports:
      - 8080:8083
    environment:
      - DISCOVERY_URL=http://eureka:8761/eureka
      - DISCOVERY_HOST=eureka
    depends_on:
      - db
      - quiz-service
      - question-service
    volumes:
      - ./ApiGateway/ApiGateway/target/ApiGateway-0.0.1-SNAPSHOT.jar:/app/application.jar
